<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { governanceStatusLabels, reportCategories, sanctionLabels, type GovernanceActionDto, type GovernanceAppealDto, type GovernanceDecisionInput, type GovernanceQueueDto, type GovernanceReportDto, type GovernanceReviewDto, type GovernanceTarget, type GovernanceTargetDto } from '@ai-learning-hub/contracts'
import { communityAdminApi } from '../services/community'
import { useSessionStore } from '../stores/session'
import AdminDialog from './AdminDialog.vue'
import AdminPagination from './AdminPagination.vue'
const props = defineProps<{ target?: { type: 'post' | 'comment'; id: string; revision: number; title: string } | null }>()
const emit = defineEmits<{ review: [id: string]; inspect: [id: string]; closed: [] }>()
const session = useSessionStore()
const canBan = computed(() => session.user?.permissions.includes('user.write') && session.user?.permissions.includes('user.session.revoke'))
const query = reactive({ kind: 'reviews', status: 'pending', assigned: 'all', category: '', targetType: '', keyword: '', overdue: false, page: 1, pageSize: 20 })
const state = ref<GovernanceQueueDto>({ reports: [], appeals: [], reviews: [], total: 0, page: 1, pageSize: 20 })
const busy = ref(false), error = ref(''), notice = ref(''), open = ref(false)
const report = ref<GovernanceReportDto | null>(null), appeal = ref<GovernanceAppealDto | null>(null), appealedAction = ref<GovernanceActionDto | null>(null)
const appealedReview = ref<GovernanceReviewDto | null>(null), historyOpen = ref(false), history = ref<{ target: GovernanceTargetDto; actions: GovernanceActionDto[] } | null>(null), revokeReason = ref('')
const action = ref<GovernanceDecisionInput['action'] | 'approve' | 'limit' | 'label' | 'restore'>('warn'), reason = ref(''), ruleCode = ref(''), expiresAt = ref(''), operation = ref<NonNullable<GovernanceDecisionInput['operation']>>('post'), label = ref('')
let loadEpoch = 0, requestKey = ''
const date = (value: string) => new Date(value).toLocaleString('zh-CN')
const load = async () => {
  const epoch = ++loadEpoch; error.value = ''
  try { const data = await communityAdminApi.governance(Object.fromEntries(Object.entries(query).filter(([, value]) => value !== ''))); if (epoch === loadEpoch) state.value = data }
  catch (cause) { if (epoch === loadEpoch) error.value = cause instanceof Error ? cause.message : '工作台加载失败' }
}
const run = async (task: () => Promise<unknown>) => {
  if (busy.value) return
  busy.value = true; error.value = ''; notice.value = ''
  try { await task(); await load() } catch (cause) { error.value = cause instanceof Error ? cause.message : '操作失败，请刷新' }
  finally { busy.value = false }
}
const claim = (kind: string, id: string, revision: number) => run(() => communityAdminApi.claim(kind, id, revision))
const release = (kind: string, id: string, revision: number) => run(() => communityAdminApi.release(kind, id, revision))
const mayRelease = (id: string | null) => !!id && (id === session.user?.id || session.user?.roles.includes('super_admin'))
const showHistory = (type: string, id: string) => run(async () => { history.value = await communityAdminApi.history(type, id); revokeReason.value = ''; historyOpen.value = true })
const revoke = (row: GovernanceActionDto) => run(async () => { await communityAdminApi.revokeSanction(row.id, row.revision, revokeReason.value); history.value = await communityAdminApi.history(history.value!.target.type, history.value!.target.id); notice.value = '已撤销对应处罚，当前审核和其他处罚继续生效。' })
const reset = () => { reason.value = ''; ruleCode.value = ''; expiresAt.value = ''; error.value = ''; label.value = ''; appealedAction.value = null; appealedReview.value = null; requestKey = globalThis.crypto?.randomUUID?.() || `governance-${Date.now()}-${Math.random().toString(36).slice(2)}` }
const openReport = (row: GovernanceReportDto) => { reset(); report.value = row; appeal.value = null; action.value = 'warn'; open.value = true }
const openAppeal = (row: GovernanceAppealDto) => run(async () => { reset(); report.value = null; appeal.value = row; action.value = 'reject'; const detail = await communityAdminApi.appealDetail(row.id); appealedAction.value = detail.action; appealedReview.value = detail.review; open.value = true })
const save = () => run(async () => {
  if (appeal.value) await communityAdminApi.appealDecision(appeal.value.id, { expectedRevision: appeal.value.revision, action: action.value as 'approve' | 'reject', reason: reason.value })
  else if (props.target && !report.value && ['limit', 'label', 'restore'].includes(action.value)) await communityAdminApi.moderate(props.target.type, props.target.id, { action: action.value as 'limit' | 'label' | 'restore', reason: reason.value, ...(action.value === 'label' ? { label: label.value } : {}) })
  else {
    const input: GovernanceDecisionInput = { expectedRevision: report.value?.revision || props.target!.revision, action: action.value as GovernanceDecisionInput['action'], reason: reason.value, ruleCode: ruleCode.value, ...(report.value?.target.currentRevision ? { expectedContentRevision: report.value.target.currentRevision } : {}), ...(action.value === 'restrict' ? { operation: operation.value } : {}), ...(expiresAt.value ? { expiresAt: new Date(expiresAt.value).toISOString() } : {}) }
    if (report.value) await communityAdminApi.reportDecision(report.value.id, input)
    else await communityAdminApi.sanction(props.target!.type as GovernanceTarget, props.target!.id, input, requestKey)
  }
  open.value = false; notice.value = '处理与通知已保存。'
})
watch(() => props.target, (target) => { if (target) { reset(); report.value = null; appeal.value = null; action.value = 'warn'; open.value = true } }, { immediate: true })
watch(open, (value) => { if (!value) emit('closed') })
watch(() => [query.kind, query.status, query.assigned, query.overdue], () => { query.page = 1; void load() })
onMounted(load)
</script>
<template><section class="community-admin-section">
  <nav class="community-admin-tabs" aria-label="治理事项"><button v-for="[key, title] in [['reviews','待复核'],['reports','举报'],['appeals','申诉'],['processing','处理中事项']]" :key="key" :class="{ active: query.kind === key }" @click="query.kind = key">{{ title }}</button></nav>
  <form class="community-admin-filter" @submit.prevent="query.page = 1; load()"><select v-if="query.kind !== 'reviews' && query.kind !== 'processing'" v-model="query.status" aria-label="处理状态"><option value="all">全部状态</option><option v-for="(title, key) in governanceStatusLabels" :key="key" :value="key">{{ title }}</option></select><select v-model="query.assigned" aria-label="领取筛选"><option value="all">全部负责人</option><option value="mine">我领取的</option><option value="unassigned">未领取</option></select><select v-if="query.kind === 'reports'" v-model="query.category" aria-label="举报分类"><option value="">全部分类</option><option v-for="(title,key) in reportCategories" :key="key" :value="key">{{ title }}</option></select><select v-if="query.kind === 'reports'" v-model="query.targetType" aria-label="举报对象"><option value="">全部对象</option><option value="post">帖子</option><option value="comment">评论</option><option value="resource">资源作品</option><option value="collection">公开合集</option><option value="profile">账号资料</option></select><input v-if="query.kind === 'reports'" v-model="query.keyword" placeholder="举报理由关键词" aria-label="举报理由关键词" maxlength="120" /><label><input v-model="query.overdue" type="checkbox" />仅看逾期</label><button class="admin-secondary">查询</button></form>
  <p class="community-admin-note">领取后处理，超出48小时显示逾期。举报数量不会自动封号；账号封禁需要用户管理权限，永久封禁只允许超级管理员。</p>
  <p v-if="error" class="error-banner" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p>
  <article v-for="row in state.reviews" :key="row.id" class="community-admin-row"><div><strong>内容 {{ row.targetType }} · 修订 {{ row.contentRevision }}</strong><p>{{ row.targetId }}</p><small>规则版本 {{ row.ruleVersion }} · {{ row.assignedToId ? '已领取' : '待领取' }} · 截止 {{ date(row.dueAt) }} <b v-if="Date.parse(row.dueAt) < Date.now()">已逾期</b></small></div><button v-if="!row.assignedToId" class="admin-secondary" :disabled="busy" @click="claim('reviews', row.id, row.contentRevision)">领取</button><button v-if="mayRelease(row.assignedToId)" class="admin-secondary" :disabled="busy" @click="release('reviews', row.id, row.contentRevision)">退回待领取</button><button class="admin-secondary" @click="emit('review', row.id)">查看并复核</button></article>
  <article v-for="row in state.reports" :key="row.id" class="community-admin-row"><div><strong>{{ governanceStatusLabels[row.status] }} · {{ reportCategories[row.category] }}</strong><p>{{ row.target.title }} · 修订 {{ row.target.revision ?? '未知，需重新核对' }}</p><p>{{ row.reason }} {{ row.description }}</p><a v-for="url in row.evidence" :key="url" :href="url" target="_blank" rel="noopener noreferrer">证据链接 </a><p v-if="row.resultReason">处理记录：{{ row.resultReason }}</p><small>截止 {{ date(row.dueAt) }} <b v-if="['pending','reviewing'].includes(row.status) && Date.parse(row.dueAt) < Date.now()">已逾期</b></small></div><button v-if="['post','resource'].includes(row.target.type) && row.target.available" class="admin-secondary" @click="emit('inspect', row.target.id)">内容详情</button><button v-if="row.status === 'pending' && !row.assignedToId" class="admin-secondary" :disabled="busy" @click="claim('reports', row.id, row.revision)">领取</button><button v-if="row.status === 'reviewing' && row.assignedToId === session.user?.id" class="admin-primary" :disabled="busy" @click="openReport(row)">处理</button><button class="admin-secondary" :disabled="busy" @click="showHistory(row.target.type, row.target.id)">内容与记录</button><button v-if="row.status === 'reviewing' && mayRelease(row.assignedToId)" class="admin-secondary" :disabled="busy" @click="release('reports', row.id, row.revision)">退回待领取</button></article>
  <article v-for="row in state.appeals" :key="row.id" class="community-admin-row"><div><strong>{{ governanceStatusLabels[row.status] }} · {{ row.actionId ? '处罚申诉' : '内容修订申诉' }}</strong><p>{{ row.reason }}</p><p v-if="row.resultReason">处理记录：{{ row.resultReason }}</p><small>截止 {{ date(row.dueAt) }} <b v-if="['pending','reviewing'].includes(row.status) && Date.parse(row.dueAt) < Date.now()">已逾期</b></small></div><button v-if="row.status === 'pending' && !row.assignedToId" class="admin-secondary" :disabled="busy" @click="claim('appeals', row.id, row.revision)">领取</button><button class="admin-secondary" :disabled="busy" @click="openAppeal(row)">查看申诉</button><button v-if="row.status === 'reviewing' && mayRelease(row.assignedToId)" class="admin-secondary" :disabled="busy" @click="release('appeals', row.id, row.revision)">退回待领取</button></article>
  <p v-if="!state.total" class="admin-empty">没有符合筛选条件的事项。</p><AdminPagination :page="query.page" :page-size="query.pageSize" :total="state.total" @change="query.page = $event; load()" />
  <AdminDialog v-model="open" :title="appeal ? '复核申诉' : '记录治理决定'"><form class="admin-form" @submit.prevent="save"><p v-if="report">{{ report.target.title }}</p><p v-else-if="!appeal">{{ target?.title }} · 修订 {{ target?.revision }} <button v-if="target" type="button" class="admin-secondary" @click="showHistory(target.type, target.id)">处理记录与撤销</button></p><template v-if="appeal"><p>{{ appeal.reason }}</p><a v-for="url in appeal.evidence" :key="url" :href="url" target="_blank" rel="noopener noreferrer">申诉证据 </a><p v-if="appealedAction">{{ sanctionLabels[appealedAction.action] }}：{{ appealedAction.reason }}<br />依据 {{ appealedAction.ruleCode }} · {{ appealedAction.expiresAt ? date(appealedAction.expiresAt) : '无到期时间' }}</p><p v-if="appealedReview">对象 {{ appealedReview.targetType }} · 修订 {{ appealedReview.contentRevision }} · 规则版本 {{ appealedReview.ruleVersion }}<br />原理由：{{ appealedReview.reason }}<button type="button" class="admin-secondary" @click="emit('review', appealedReview.id)">查看涉及修订</button></p></template>
  <label>决定<select v-model="action"><template v-if="appeal"><option value="reject">驳回申诉</option><option value="approve">同意申诉并撤销对应处理</option></template><template v-else><option v-if="report" value="reject">驳回举报</option><option v-for="(title,key) in sanctionLabels" v-show="key !== 'ban' || canBan" :key="key" :value="key">{{ title }}</option><template v-if="!report && target?.type === 'post'"><option value="limit">限制展示（原功能）</option><option value="label">内容说明标签（原功能）</option></template><option v-if="!report && target" value="restore">恢复历史隐藏内容</option></template></select></label>
  <label v-if="!appeal && !['limit','label','restore'].includes(action)">规则依据<input v-model="ruleCode" required minlength="2" maxlength="100" placeholder="具体社区规则条款或检测规则编号" /></label><label v-if="action === 'label'">说明标签<input v-model="label" required maxlength="60" /></label><label v-if="action === 'restrict'">限制功能<select v-model="operation"><option value="post">发帖</option><option value="comment">评论</option><option value="upload">上传</option><option value="interaction">互动</option><option value="profile">公开资料</option><option value="collection">公开合集</option><option value="report">举报</option></select></label><label v-if="['restrict','mute','takedown','ban'].includes(action)">期限<input v-model="expiresAt" type="datetime-local" :required="['restrict','mute'].includes(action) || action === 'ban' && !session.user?.roles.includes('super_admin')" /></label><label>处理理由<textarea v-model="reason" required minlength="4" maxlength="500" rows="4" /></label><p>只解除对应处罚；新的内容审核、删除及其他处罚仍生效。申诉须由非原处理人决定。</p><p v-if="error" class="error-banner" role="alert">{{ error }}</p><button class="admin-primary" :disabled="busy || !!appeal && (appeal.status !== 'reviewing' || appeal.assignedToId !== session.user?.id)">保存决定</button></form></AdminDialog>
  <AdminDialog v-model="historyOpen" title="涉及内容与处理记录"><template v-if="history"><h3>{{ history.target.title }}</h3><p>当前修订 {{ history.target.revision }}</p><pre class="governance-content">{{ history.target.text || '当前内容已不可用或为私人草稿。' }}</pre><label>撤销理由<input v-model="revokeReason" minlength="4" maxlength="500" placeholder="核查当前状态后填写理由" /></label><article v-for="row in history.actions" :key="row.id" class="community-admin-row"><div><strong>{{ sanctionLabels[row.action] }} · 修订 {{ row.target.revision ?? '历史记录' }}</strong><p>依据 {{ row.ruleCode }} · {{ row.reason }}</p><p>{{ row.revokedAt ? '已撤销：' + row.revokeReason : row.active ? '当前生效' : '已到期或尚未开始' }} · {{ row.expiresAt ? date(row.expiresAt) : '无到期时间' }}</p></div><button v-if="!row.revokedAt" class="admin-secondary" :disabled="busy || revokeReason.trim().length < 4" @click="revoke(row)">撤销此处罚</button></article><p v-if="!history.actions.length">暂无治理处罚记录。</p></template><p v-if="error" class="error-banner" role="alert">{{ error }}</p></AdminDialog>
</section></template>
<style scoped>.governance-content{white-space:pre-wrap;overflow-wrap:anywhere;max-height:320px;overflow:auto;font:inherit}</style>
