import type { CommunityContentBlock, CommunityPostType } from '../../../contracts/src/community'

export interface LczCuratedPost {
  sourceKey: `lcz:${number}`
  sourceUrl: `https://lcz.me/topic/${number}`
  sourceAuthor: string
  sourcePublishedAt: string
  category: 'llm' | 'agent' | 'media' | 'hardware'
  postType: Extract<CommunityPostType, 'note' | 'general'>
  themeSlug: 'llm' | 'agent' | 'image' | 'hardware'
  adaptedTitle: string
  adaptedBlocks: CommunityContentBlock[]
  topics: string[]
  imageSources: Array<{ sourceUrl: string; alt: string }>
}

const curated = (
  source: Omit<LczCuratedPost, 'adaptedBlocks' | 'imageSources'>,
  sections: string[],
): LczCuratedPost => ({
  ...source,
  adaptedBlocks: [
    ...sections.map((text): CommunityContentBlock => ({ type: 'paragraph', text })),
    {
      type: 'paragraph',
      text: `参考来源：抡锤者社区\n原作者：${source.sourceAuthor}\n原帖：${source.sourceUrl}\n说明：本文经过 AI MAKER CAMPUS 编辑整理，标题、结构和表述均已重新编写。`,
    },
  ],
  imageSources: [],
})

export const lczCuratedPosts: LczCuratedPost[] = [
  curated({
    sourceKey: 'lcz:1356',
    sourceUrl: 'https://lcz.me/topic/1356',
    sourceAuthor: 'Michael Zhou',
    sourcePublishedAt: '2026-08-27T09:20:33.175Z',
    category: 'llm',
    postType: 'note',
    themeSlug: 'llm',
    adaptedTitle: '长上下文服务中，HiCache 何时真正有价值？',
    topics: ['community-topic-attention', 'community-topic-observability'],
  }, [
    '学习背景｜本帖整理自一组单卡长上下文实验。测试环境为 RTX 4090 48GB、Ubuntu 主机内存 62GB、Qwen3.8-27B FP8 与 SGLang 0.5.17，目标上下文为 256K。关注点不是“能否启动”，而是三级 KV 缓存对可用容量和首字延迟的实际影响。',
    '核心结论｜L1 可容纳 270,278 tokens，约占 8.6GB；设置 24GB HiCache L2 后，记录到 504,447 tokens 的缓存容量。重复前缀命中约 88.5% 时，首字延迟由冷请求约 2.6 秒降到约 0.67 秒。关闭思考时生成约 63～76 tok/s，开启思考时约 35～47 tok/s。',
    '实践步骤｜先固定模型、上下文和并发，再分别记录冷请求与热请求；随后只改变 L2 容量，比较前缀命中、TTFT、主存占用和吞吐。对混合 Mamba/Attention 架构，实验中还需要把 page size 设为 1，否则组合 HiCache 时会出现段错误。',
    '常见问题与风险边界｜缓存扩大不是免费提速：它会持续占用主存，并且收益依赖重复前缀。上述数字只适用于该模型、版本和硬件组合，不能直接外推到不同架构或多并发服务。生产评估还要补充长时间运行、缓存淘汰和失败恢复。',
    '留给社区的讨论问题｜如果你的课程项目只有少量长对话，是优先增加上下文上限，还是优先保证热前缀命中与更低 TTFT？你会用什么指标决定 L2/L3 缓存的容量？',
  ]),
  curated({
    sourceKey: 'lcz:1404',
    sourceUrl: 'https://lcz.me/topic/1404',
    sourceAuthor: 'jingy yi',
    sourcePublishedAt: '2026-08-29T13:35:09.214Z',
    category: 'llm',
    postType: 'note',
    themeSlug: 'llm',
    adaptedTitle: '同一张 4080S 32GB，如何比较 llama.cpp 与 SGLang？',
    topics: ['community-topic-gpu', 'community-topic-observability'],
  }, [
    '学习背景｜原实验在 RTX 4080S 32GB、驱动 595.84 上比较两条本地推理路线：llama.cpp 使用 Qwen3.8-27B UD-Q4_K_XL，SGLang 使用 AWQ。重点是让模型格式、缓存和推理特性进入比较，而不是只看一条最高速度。',
    '核心结论｜llama.cpp 在该环境中不启用 MTP 时约 31 tok/s，MTP n=4 时最高约 64 tok/s；量化 KV 为 q4_0 可节省约 3.3GB。35K 冷预填充约 1,900 tok/s，解码中位数约 89 tok/s，显存约 31.0/32.8GB。SGLang AWQ 记录为 36.9 tok/s，本次 HiCache 检索未按预期生效。',
    '实践步骤｜先在 llama.cpp 中固定上下文与批次，分别测无 MTP、不同 MTP 步数及 q4_0 KV；再在 SGLang 中固定 AWQ 模型，独立验证服务启动、缓存命中与真实请求。每组都保留显存、预填充、解码和首字延迟，而不是混成一个“总速度”。',
    '常见问题与风险边界｜Ada 架构在本次环境中不支持所尝试的 NVFP4 路线；HiCache 未命中也不能直接推导为功能无效，需要继续核对版本、参数和请求前缀。不同量化文件、提示长度和 MTP 接受率会显著改变结果。',
    '留给社区的讨论问题｜课程实验里比较两个推理后端时，你会如何设计同输入、同输出长度、同缓存状态的对照，避免把格式差异误当成框架差异？',
  ]),
  curated({
    sourceKey: 'lcz:1429',
    sourceUrl: 'https://lcz.me/topic/1429',
    sourceAuthor: 'rock shi',
    sourcePublishedAt: '2026-08-31T03:32:32.613Z',
    category: 'llm',
    postType: 'note',
    themeSlug: 'llm',
    adaptedTitle: '工具调用解析反复失败，先核对模型对应的 Parser',
    topics: ['community-topic-tool-calling', 'community-topic-observability'],
  }, [
    '学习背景｜在 vLLM 托管 Qwen3.8-27B FP8 的工具调用场景中，服务最初沿用 Hermes 解析方式。运行约 6 天后累计出现 94 次 qwen3xml 解析错误，说明“接口可用”并不等于工具调用协议稳定。',
    '核心结论｜切换为 qwen3_coder 对应的 tool-call parser 后，连续 18.5 小时、2,265 次 completion 没有再记录同类解析错误。差异来自协议解析策略：qwen3_xml 更依赖严格 XML 结构，qwen3_coder 使用的匹配方式对本次输出更合适。',
    '实践步骤｜先从服务日志聚合同一错误指纹并统计基线；确认模型实际输出格式后，只替换 parser，不同时改模型、采样和工具定义；最后用足够长的请求窗口比较失败数与成功调用数。',
    '常见问题与风险边界｜这不是“qwen3_coder 永远更好”的结论。Parser 必须与检查点、聊天模板和客户端消息格式匹配；短时零错误也不能替代回归测试。切换前应保留可回滚配置。',
    '留给社区的讨论问题｜你的 Agent 实训是否记录了“模型回答成功但工具参数解析失败”这一类中间状态？除了错误数，还应观察哪些协议质量指标？',
  ]),
  curated({
    sourceKey: 'lcz:1422',
    sourceUrl: 'https://lcz.me/topic/1422',
    sourceAuthor: '清风明月',
    sourcePublishedAt: '2026-08-30T11:07:01.134Z',
    category: 'llm',
    postType: 'note',
    themeSlug: 'llm',
    adaptedTitle: '本地 Qwen 的思考强度为什么不能只改一个字段？',
    topics: ['community-topic-prompt', 'community-topic-tool-calling'],
  }, [
    '学习背景｜在 DeepSeek Harness 接入本地 Qwen3.8-27B 时，仅配置 reasoningEfforts 并不能稳定控制思考开关。问题涉及客户端强度名称、兼容层格式和聊天模板参数三层映射。',
    '核心结论｜原实验需要同时指定 compat.thinkingFormat 为 chat-template，并把不同强度映射到 chatTemplateKwargs。off 对应 enable_thinking=false，low、medium、xhigh 再分别传递相应设置；该版本中 high 不是有效档位。',
    '实践步骤｜先确认客户端允许的强度枚举，再检查发往推理服务的最终请求；为 off、low、medium、xhigh 各跑一次最小提示，比较请求参数和响应中的思考表现。YAML 中的 off 建议加引号，避免被解析为布尔值。',
    '常见问题与风险边界｜强度名与兼容格式可能随 Harness、模板或服务版本变化，不能把这组映射复制到其他模型后直接宣称有效。验证要同时包含健康检查、无界面调用和实际输出采样。',
    '留给社区的讨论问题｜你会把“思考强度生效”定义为参数成功送达、输出格式变化，还是任务质量变化？如何建立三者之间的证据链？',
  ]),
  curated({
    sourceKey: 'lcz:1157',
    sourceUrl: 'https://lcz.me/topic/1157',
    sourceAuthor: 'exllm',
    sourcePublishedAt: '2026-08-17T07:32:31.931Z',
    category: 'llm',
    postType: 'note',
    themeSlug: 'llm',
    adaptedTitle: '7900 XTX 本地编码任务：速度数字应如何解读？',
    topics: ['community-topic-gpu', 'community-topic-observability'],
  }, [
    '学习背景｜原帖记录了 Ryzen 5 5600、32GB 内存、RX 7900 XTX 与 Ubuntu 26.04 上的本地编码任务。推理后端为 llama.cpp Vulkan，模型是 Qwen3.8-27B Q5_K_M，并通过 DeepSeek Harness 发起真实任务。',
    '核心结论｜一组 4,098 输入 tokens、277 输出 tokens 的任务记录为约 50.72 tok/s；Harness 汇总的平均生成速度约 52 tok/s，缓存命中约 98%。另一次较短生成达到 89.31 tok/s，说明单个峰值不能代表长任务体验。',
    '实践步骤｜配置中使用 131,072 上下文、parallel=2、MTP n=3 和 q8 KV。复现实验时应分别保存提示长度、输出长度、缓存命中、预填充与解码速度，再以完整编码任务是否完成作为业务验收。',
    '常见问题与风险边界｜帖子使用的是特定 Vulkan 构建版本，操作系统版本、模型量化和上下文都会影响结果。高缓存命中会掩盖冷启动成本；89.31 tok/s 不应脱离那次请求长度单独宣传。',
    '留给社区的讨论问题｜本地 Coding Agent 的课程作业中，你更看重平均解码速度、首字延迟，还是一次完整修改通过测试所需的总时间？',
  ]),
  curated({
    sourceKey: 'lcz:1319',
    sourceUrl: 'https://lcz.me/topic/1319',
    sourceAuthor: '王池川',
    sourcePublishedAt: '2026-08-25T15:37:12.932Z',
    category: 'agent',
    postType: 'general',
    themeSlug: 'agent',
    adaptedTitle: '评估 Coding Agent，先看完整任务闭环',
    topics: ['community-topic-agent-evaluation', 'community-topic-tool-calling'],
  }, [
    '学习背景｜这组实验没有用简单问答衡量 Agent，而是在 Windows 10、Python 3.14.3、仅标准库且断网的约束下，安排 5 个会真实遇到的工程任务，并要求完成验证。',
    '核心结论｜5 项任务合计耗时 24 分 48 秒，记录 61 个 Agent 步骤和 71 次工具调用。MCP 服务测试 12/12 通过，基准检查 20/20 通过；独立复核仍找到 8 项 Low/Info 问题，但干净环境复现通过。',
    '实践步骤｜先写清环境限制、输入仓库和验收命令；执行过程中记录每次工具调用与返工；完成后由独立检查重新安装、运行测试和审阅低风险问题。速度、正确性和可复现性分别统计。',
    '常见问题与风险边界｜完成任务不等于代码没有问题，自动测试通过也不替代独立审阅。这里的耗时只代表这 5 个任务与该环境，不能外推为产品排名；估算值也要和实测值分开。',
    '留给社区的讨论问题｜如果你只能为课程中的 Agent 评测保留三个指标，会选择总完成时间、工具调用数、测试通过率、返工次数还是独立审查问题数？为什么？',
  ]),
  curated({
    sourceKey: 'lcz:1116',
    sourceUrl: 'https://lcz.me/topic/1116',
    sourceAuthor: 'kop wang',
    sourcePublishedAt: '2026-08-14T08:35:13.950Z',
    category: 'agent',
    postType: 'note',
    themeSlug: 'agent',
    adaptedTitle: '把业务验收写在前面：Vibe Coding 的协作方法',
    topics: ['community-topic-agent-evaluation', 'community-topic-multi-agent'],
  }, [
    '学习背景｜当开发者把大量实现交给 Coding Agent 后，真正稀缺的能力从“逐行输入代码”转向目标定义、过程约束和结果验收。原讨论的价值在于把人机协作拆成可执行职责，而不是只描述工具体验。',
    '核心结论｜人仍需负责方向、目标、边界与验收，并在关键节点管理步骤；模型能力决定上限，运行框架决定它能否稳定使用工具和保持上下文。测试应表达业务行为，不应只是照抄当前实现。',
    '实践步骤｜先用业务语言写成功条件与失败条件；让 Agent 交付最小实现和对应测试；每完成一个可验证阶段就检查真实输入输出；遇到偏离时修正目标或约束，而不是无限追加提示。',
    '常见问题与风险边界｜“完全放手”容易让错误方向积累。只看代码数量、对话流畅度或单次演示会高估完成度；TDD 若复制实现细节，也会形成代码与测试同时出错的假安全。',
    '留给社区的讨论问题｜你最近一次使用 Coding Agent 时，哪条验收条件如果提前写清，最能减少返工？它能否由另一位同学独立验证？',
  ]),
  curated({
    sourceKey: 'lcz:697',
    sourceUrl: 'https://lcz.me/topic/697',
    sourceAuthor: 'alanwoo',
    sourcePublishedAt: '2026-06-25T15:05:14.160Z',
    category: 'agent',
    postType: 'note',
    themeSlug: 'agent',
    adaptedTitle: 'Agent 请求失败时，别忽略输出上限与上下文预算',
    topics: ['community-topic-tool-calling', 'community-topic-observability'],
  }, [
    '学习背景｜Hermes 0.17.0 通过 vLLM 0.23.0 调用 Qwen3.6-27B FP8 时，服务部署在 Ubuntu 24.04.4。表面现象像是本地模型不兼容，实际问题出在默认输出预算与现有上下文冲突。',
    '核心结论｜当请求默认携带 65,536 的输出上限时，提示长度与输出预算合计超过上下文，服务会拒绝请求。把该次请求的 max_tokens 明确设为 8,192 后恢复。',
    '实践步骤｜先从服务端错误中区分模型加载、协议解析和 token 预算；记录提示 tokens、模型上下文上限与 max_tokens；用一个保守输出值验证，再根据任务实际需要逐步调整。',
    '常见问题与风险边界｜8,192 不是通用最佳值，只是本次环境的有效修复。过度压低会截断长任务，过高则挤占输入空间；模型上下文、并发槽位和客户端默认值升级后都要重新核对。',
    '留给社区的讨论问题｜你的 Agent 客户端是否在界面上展示输入预算、输出预算和剩余上下文？如果没有，最小可观测性应该放在哪里？',
  ]),
  curated({
    sourceKey: 'lcz:1159',
    sourceUrl: 'https://lcz.me/topic/1159',
    sourceAuthor: 'kop wang',
    sourcePublishedAt: '2026-08-17T08:59:09.623Z',
    category: 'agent',
    postType: 'note',
    themeSlug: 'agent',
    adaptedTitle: '本地模型角色冲突：在兼容层做最小适配',
    topics: ['community-topic-tool-calling', 'community-topic-prompt'],
  }, [
    '学习背景｜DeepSeek Harness 调整推理强度时，请求中的角色可能变为 developer；原帖所用的本地 vLLM/SGLang 配置只按 system 与 user 处理，因而出现 400 错误。',
    '核心结论｜一个窄适配插件在发出请求前重写不被当前模板接受的角色，同时保留 reasoning effort，解决了该环境的角色冲突。修复点位于协议边界，不需要改模型权重或业务任务。',
    '实践步骤｜先抓取最小失败请求，确认是角色枚举而非正文触发；在适配层只转换不兼容角色，并保留原有内容顺序和推理参数；最后覆盖普通问答、工具调用与不同强度。',
    '常见问题与风险边界｜这是特定客户端、模板和后端组合的观察，不能宣称所有 vLLM/SGLang 都不支持 developer。角色重写可能改变系统指令优先级，必须验证安全约束没有被降级。',
    '留给社区的讨论问题｜协议兼容应该由 Agent 客户端、网关还是模型服务负责？怎样避免多个适配层重复改写同一条消息？',
  ]),
  curated({
    sourceKey: 'lcz:694',
    sourceUrl: 'https://lcz.me/topic/694',
    sourceAuthor: 'kop wang',
    sourcePublishedAt: '2026-06-25T09:46:13.012Z',
    category: 'agent',
    postType: 'note',
    themeSlug: 'agent',
    adaptedTitle: 'Agent 工具升级故障时，先建立可逆回滚',
    topics: ['community-topic-agent-evaluation', 'community-topic-observability'],
  }, [
    '学习背景｜原帖发布于 2026-06-25，记录 OpenCode 1.17.10 在使用中频繁崩溃的版本故障。后续版本已处理问题，因此它更适合作为升级与回滚流程案例，而不是当前版本告警。',
    '核心结论｜当时有效的临时恢复方法是回退到 1.17.09，并关闭自动更新，等待修复版本。关键经验是先恢复可工作的已知版本，再保留现场信息定位，而不是在生产任务中持续试错。',
    '实践步骤｜升级前记录当前版本和配置；出现重复崩溃后保存最小日志，切回已验证版本；禁用自动升级避免再次覆盖；在隔离环境验证新版本后再恢复升级。',
    '常见问题与风险边界｜版本号和故障结论具有时间性，不能把 2026-06-25 的处理直接用于今天。回滚还需确认配置格式与数据是否向后兼容；课程项目至少要保留备份与恢复验证。',
    '留给社区的讨论问题｜你会为 Coding Agent 工具的升级设置哪些门禁：自动测试、真实任务烟测、配置备份，还是一键回滚？',
  ]),
  curated({
    sourceKey: 'lcz:1306',
    sourceUrl: 'https://lcz.me/topic/1306',
    sourceAuthor: 'rock shi',
    sourcePublishedAt: '2026-08-25T09:23:47.771Z',
    category: 'media',
    postType: 'note',
    themeSlug: 'image',
    adaptedTitle: '3080 20GB 跑 MiniMax H3：把加速收益拆开测',
    topics: ['community-topic-comfyui', 'community-topic-gpu'],
  }, [
    '学习背景｜原实验使用魔改 RTX 3080 20GB、ComfyUI 0.30 便携环境、Python 3.13、PyTorch 2.9.1+cu130，组合 H3 pruned INT8、NVFP4、Turbo LoRA 与 SageAttention 2.2.0。',
    '核心结论｜在 768P、5 秒视频条件下，10 步任务记录约 541～604 秒，4 步约 349 秒，加入 Sage 后约 279.7 秒；10 秒任务从约 1,012 秒下降到约 757.8 秒。不同加速项应分别验证，不能只报告最终最快值。',
    '实践步骤｜固定分辨率、时长、步数、模型和种子；先跑基线，再只改 Turbo 步数，最后加入 Sage；每次记录总墙钟、显存峰值与输出是否可用。安装前还要核对 Sage 版本，PyPI 上的 1.0.6 并非帖子使用的 2.2.0。',
    '常见问题与风险边界｜Windows 社区 wheel 必须匹配 Python、PyTorch 与 CUDA。WDDM 环境中出现 GPU 丢失时，应先停止批量任务并核对驱动稳定性；单次成功不代表长时间队列可靠。',
    '留给社区的讨论问题｜视频生成实验中，速度提升到什么程度才值得接受步数减少或更复杂的依赖安装？你会怎样加入质量盲评？',
  ]),
  curated({
    sourceKey: 'lcz:1125',
    sourceUrl: 'https://lcz.me/topic/1125',
    sourceAuthor: 'Bunsei',
    sourcePublishedAt: '2026-08-14T20:05:45.070Z',
    category: 'media',
    postType: 'note',
    themeSlug: 'image',
    adaptedTitle: 'ComfyUI 加速是否有效，要用固定工作流做 A/B',
    topics: ['community-topic-comfyui', 'community-topic-gpu'],
  }, [
    '学习背景｜原帖在 Windows 11、R7 9700X、48GB DDR5-6000 与 Radeon AI PRO R9700 上测试 ComfyUI 0.33.1、ROCm 7.14、PyTorch 2.12 的注意力与显存选项。',
    '核心结论｜同一个 8 秒、0.4MP、seed 43 的工作流，基线约 284.44 秒；启用 CK Attention 与动态显存相关参数后记录约 180.02 秒，约为 1.6 倍速度。结论来自固定条件的 A/B，而不是跨工作流比较。',
    '实践步骤｜保留同一输入、种子、分辨率、时长和模型；清晰记录启动参数；每组至少重复运行并核对输出完整性。参数包括 use-ck-attention 与 enable-dynamic-vram，但应逐项拆开确认各自贡献。',
    '常见问题与风险边界｜结果绑定于当时的软件栈与 GPU。动态显存对不同系统和架构的稳定性差异较大，不能把一次加速直接当作推荐默认值；还需观察多轮运行后的显存释放。',
    '留给社区的讨论问题｜如果两项优化一起启用后快了 1.6 倍，你会怎样设计下一轮消融实验来判断真正有效的是哪一项？',
  ]),
  curated({
    sourceKey: 'lcz:1244',
    sourceUrl: 'https://lcz.me/topic/1244',
    sourceAuthor: 'Rex Fan',
    sourcePublishedAt: '2026-08-21T06:11:48.167Z',
    category: 'media',
    postType: 'general',
    themeSlug: 'image',
    adaptedTitle: '视频生成硬件比较：先区分单条延迟与批量产能',
    topics: ['community-topic-comfyui', 'community-topic-gpu'],
  }, [
    '学习背景｜原帖用同一套 MiniMax H3 ComfyUI 视频生视频工作流比较 RTX PRO 6000 96GB 与单台 DGX Spark 128GB 统一内存。流程为 960×544 首阶段、2 倍 3D latent 与 refine 到 1920×1088，LoRA 0.3、12 steps，显存约 67～69GB。',
    '核心结论｜PRO 6000 处理 90/124/158 帧分别约 10.4/17.9/27.0 分钟；Spark 分别约 36.3/61.1/86 分钟，单台吞吐约为 PRO 的 29%～32%。PRO 更适合低单条延迟，Spark 的统一内存与多机并行更适合批量候选。',
    '实践步骤｜比较时锁定输入、分辨率、帧数、LoRA 和步数；分别记录单条墙钟、批量并行吞吐、显存与功耗。原记录中 Spark 负载约 80～95W、SoC 约 90～95°C，PRO 约 300W、GPU 约 80°C，可作为散热观察而非统一结论。',
    '常见问题与风险边界｜价格会快速变化，本编辑稿不沿用价格判断。多台机器的理论吞吐相加不等于任务调度后的真实产能；不同分辨率下比例也会变化，480p 记录与高分辨率结果不能混算。',
    '留给社区的讨论问题｜面向课程视频项目，你会优先优化“修改后立即预览”的单条延迟，还是夜间批量生成候选的总吞吐？',
  ]),
  curated({
    sourceKey: 'lcz:1074',
    sourceUrl: 'https://lcz.me/topic/1074',
    sourceAuthor: 'qw er',
    sourcePublishedAt: '2026-08-10T05:36:05.749Z',
    category: 'media',
    postType: 'note',
    themeSlug: 'image',
    adaptedTitle: 'Linux + ROCm 动态显存失败：先区分 VBAR 与 OOM',
    topics: ['community-topic-comfyui', 'community-topic-observability'],
  }, [
    '学习背景｜原问题发生在 RX 7900 XTX、Linux 6.8、Python 3.10.12、ComfyUI 0.31.0、PyTorch 2.11.0+rocm7.2 与 comfy-aimdo 0.4.13。大型视频工作流在模型加载或 VAE 解码阶段失败。',
    '核心结论｜错误指向 VBAR 虚拟地址预留失败，而不是普通显存耗尽：当时仍有 VRAM、系统内存和 Swap。已验证的稳定回退是关闭 dynamic VRAM，并改用 XB_ToolBox 的静态 Block Swap；动态路径只保留为实验项。',
    '实践步骤｜先保存完整环境版本和错误栈；用系统指标确认是否真实 OOM；核对依赖的官方平台支持范围；关闭动态显存验证基线，再用静态分块逐步寻找可运行配置。',
    '常见问题与风险边界｜原依赖明确以 NVIDIA 为主要支持范围，ROCm 社区移植在不同 GPU 上表现不同。不要把 Windows 上的经验直接复制到 Linux，也不要仅靠降低 VAE tile 就宣布根因解决。',
    '留给社区的讨论问题｜面对“显存相关”报错时，你会收集哪些证据来区分容量不足、地址空间预留失败和驱动内存释放问题？',
  ]),
  curated({
    sourceKey: 'lcz:872',
    sourceUrl: 'https://lcz.me/topic/872',
    sourceAuthor: 'Botio Kuo',
    sourcePublishedAt: '2026-07-19T07:59:52.780Z',
    category: 'media',
    postType: 'general',
    themeSlug: 'image',
    adaptedTitle: '单卡同时跑 ComfyUI 与 LLM：优先设计任务切换',
    topics: ['community-topic-comfyui', 'community-topic-gpu'],
  }, [
    '学习背景｜问题场景是一张 RTX 3090 同时承载 llama.cpp 的 Qwen 服务与 ComfyUI。LLM 还要供内网 Agent 使用，因此“把显存各分一半”会同时压缩上下文和生成工作流空间。',
    '核心结论｜讨论中更可行的优先级是：业务不重叠时分时复用；必须并行时再考虑减少 LLM GPU 层或 ComfyUI lowvram，但接受明显降速；长期稳定并行则采用两张卡分工。对 24GB 单卡，两个重型模型同时常驻通常不是最佳目标。',
    '实践步骤｜先画出任务时序，确认 LLM 与视频生成是否真的同时发生；为停止、卸载、启动和健康检查写可回滚脚本；若由 Agent 自动切换，控制 Agent 本身应使用不会随本地模型卸载而中断的辅助模型。',
    '常见问题与风险边界｜帖子回复中的显存和速度倍数是经验估计，不应当作严格基准。自动切换前必须备份配置，并处理请求正在执行、模型未释放和服务重启失败等状态。',
    '留给社区的讨论问题｜如果实验室只有一张 24GB 卡，你会怎样排课和排队，让文本推理与视频生成共享资源但互不打断？',
  ]),
  curated({
    sourceKey: 'lcz:1277',
    sourceUrl: 'https://lcz.me/topic/1277',
    sourceAuthor: 'Jackie Suen',
    sourcePublishedAt: '2026-08-23T05:42:52.622Z',
    category: 'hardware',
    postType: 'note',
    themeSlug: 'hardware',
    adaptedTitle: '显卡通过压力测试，为何仍会在 Linux 桌面黑屏？',
    topics: ['community-topic-gpu', 'community-topic-linux'],
  }, [
    '学习背景｜原帖记录 X99 F8 与魔改 RTX 3070 16GB 在 Ubuntu/Xorg 下的黑屏。显卡在 Windows 压力测试中通过，但 Linux 桌面仍出现 Xid、nvidia-smi 超时与图形负载触发故障。',
    '核心结论｜Windows 压测只能证明一部分硬件路径，不能替代目标系统与目标负载的稳定性验证。原环境使用驱动 595.84，glxgears 约 3 分钟可触发卡死；关闭合成或限制功耗只能延后，并未确认根因。',
    '实践步骤｜分开验证无头计算与桌面显示；记录 Xid、内核日志、nvidia-smi 响应与触发负载；一次只改变驱动、功耗或显示链路中的一项，并保留恢复入口。',
    '常见问题与风险边界｜该案例没有给出确定的硬件或驱动根因，因此不能把某个临时设置写成最终修复。魔改显存、老平台、显示服务和驱动都可能参与，需要更多交叉测试。',
    '留给社区的讨论问题｜实验室采购二手或改卡时，除了跑分，你会怎样设计 Linux 无头推理、桌面显示和长时间负载三套验收？',
  ]),
  curated({
    sourceKey: 'lcz:1482',
    sourceUrl: 'https://lcz.me/topic/1482',
    sourceAuthor: '坤坤',
    sourcePublishedAt: '2026-09-03T07:10:34.965Z',
    category: 'hardware',
    postType: 'note',
    themeSlug: 'hardware',
    adaptedTitle: '双 RX 7900 XTX 工作站：先记录并发、能耗与运维成本',
    topics: ['community-topic-gpu', 'community-topic-observability'],
  }, [
    '学习背景｜原环境为 i7-10700K、64GB DDR4、双 RX 7900 XTX、Ubuntu 22.04.5、PCIe 3.0 x8 与 ROCm 7.2，并使用源码构建的 vLLM 分支。记录同时覆盖吞吐、用电和编译运维。',
    '核心结论｜原帖观察到双并发约 85 tok/s、四并发约 40 tok/s，约 200K 上下文时约 50 tok/s；每日约 9:00 至 24:00 使用记录为 4.5kWh。多卡价值不能只看显存总量，还要考虑并发分配、编译兼容和残留进程。',
    '实践步骤｜固定模型与请求长度，分别测 1/2/4 并发和长上下文；同步记录每路吞吐、总功耗与服务异常；部署文档中保留 ROCm 编译、GLIBCXX 兼容和孤儿进程检查。',
    '常见问题与风险边界｜吞吐数字来自特定社区分支和请求，不能代表标准 vLLM。4.5kWh 是单日使用记录，不是长期平均；PCIe 链路、散热和电源余量还需独立验收。',
    '留给社区的讨论问题｜如果双卡的目标是服务一个班级，你会采用张量并行、模型分卡还是多实例？选择依据是什么？',
  ]),
  curated({
    sourceKey: 'lcz:1438',
    sourceUrl: 'https://lcz.me/topic/1438',
    sourceAuthor: 'stormaround',
    sourcePublishedAt: '2026-08-31T15:06:19.674Z',
    category: 'hardware',
    postType: 'note',
    themeSlug: 'hardware',
    adaptedTitle: '双 R9700 无 P2P 部署：通信协议可能比算力更关键',
    topics: ['community-topic-gpu', 'community-topic-observability'],
  }, [
    '学习背景｜原机器使用 Ryzen 7 5700X、128GB DDR4 与两张 R9700，尝试用 SGLang 以 TP 方式部署 Qwen3.8-27B FP8。模型权重与缓存能加载，但第一次多模态 warmup 就超时并硬退出。',
    '核心结论｜原排查将首个问题定位到非 CUDA 平台仍进入对称内存 all-gather 路径；回退到常规 all-gather 后服务启动。无 P2P 条件下，RCCL 低延迟协议表现异常，改用 NCCL_PROTO=Simple 后从约 0.94 tok/s 提升到约 23 tok/s；再加入 MTP steps=3 与 fp8_e4m3 KV 后短上下文记录约 35.6～40 tok/s。',
    '实践步骤｜先把“首次 forward 崩溃”和“运行后吞吐低”分成两个问题；验证平台门禁与回退路径；用小尺寸集合通信分别比较协议；最后才加入 MTP 与 KV 量化。长上下文再单独测 TTFT、预填充、解码与检索命中。',
    '常见问题与风险边界｜260,028 tokens 冷请求 TTFT 约 473 秒、生成约 3.6 tok/s，说明容量跑通不等于交互可用。代码补丁与协议选择需要上游审阅；文中速度不能外推到有 P2P 或不同 ROCm 版本。',
    '留给社区的讨论问题｜多卡推理课程中，怎样用最小实验判断瓶颈来自模型计算、PCIe 拓扑还是集合通信协议？',
  ]),
  curated({
    sourceKey: 'lcz:1498',
    sourceUrl: 'https://lcz.me/topic/1498',
    sourceAuthor: 'zhenyu huang',
    sourcePublishedAt: '2026-09-04T03:31:14.726Z',
    category: 'hardware',
    postType: 'note',
    themeSlug: 'hardware',
    adaptedTitle: '异构双卡部署：容量跑通后还要重新平衡分层',
    topics: ['community-topic-gpu', 'community-topic-observability'],
  }, [
    '学习背景｜原实验在 X99-AD4、E5-2686 v4、64GB 内存、RX 7900 XTX 24GB 与 7700 XT 12GB 上运行 vLLM 0.28.0、ROCm 7.2.3 和 Qwen3.8-27B W4A16 GPTQ，目标是 128K、视觉、缓存与多并发。',
    '核心结论｜修正通信和调度后，16K/32K 预填充由 561.8/452.9 提升到 682.2/644.0 tok/s。改成不等量分层后，4,096 至 130,816 输入的生成约 27.55 降至 18.06 tok/s。最终视觉配置为 18/46 分层、128K、前缀缓存、最多 4 并发。',
    '实践步骤｜先确认 Above 4G Decoding 与 ReBAR，再验证 peer copy 和集合通信；对不同显卡按容量和速度做不等量分层；分别测纯文本长上下文与最终视觉配置。热缓存下，7,552 tokens 文本请求首字由约 7.451 秒降到约 0.788 秒。',
    '常见问题与风险边界｜最终 RCCL 仍走共享内存，不能宣称高速 P2P 已打通。四并发结果不代表四个独立 128K 请求都能同时容纳；MTP 和 DFlash2 的对照条件并不完全一致，原方案最终没有保留它们。',
    '留给社区的讨论问题｜异构显卡分层时，你会怎样在显存容量、预填充速度、解码速度与视觉编码器占用之间寻找平衡？',
  ]),
  curated({
    sourceKey: 'lcz:1388',
    sourceUrl: 'https://lcz.me/topic/1388',
    sourceAuthor: 'yi song',
    sourcePublishedAt: '2026-08-28T13:30:48.329Z',
    category: 'hardware',
    postType: 'general',
    themeSlug: 'hardware',
    adaptedTitle: '双品牌显卡分工：用后端边界实现 GPU 独占',
    topics: ['community-topic-gpu', 'community-topic-linux'],
  }, [
    '学习背景｜原机器为 i5-13600KF、64GB 内存、Windows 11，一张 RX 7900 XTX 24GB 专门运行 llama.cpp，RTX 4060 Ti 负责显示和其他 CUDA 应用。目标是让一个本地服务供多个客户端共享。',
    '核心结论｜该方案不是用请求参数过滤 GPU，而是使用只枚举 AMD GPU 的 HIP 构建形成后端边界，并停用可能抢先加载的 Vulkan 动态库。128K 条件下记录预填充约 800～900 tok/s、生成约 34 tok/s；降压后推理功耗约 270～290W。',
    '实践步骤｜先明确两张卡的职责与显示输出；只保留一个预期推理后端；统一服务端口与模型标识，确保客户端名称和当前加载的 GGUF 对齐；再分别验证思考开关、上下文档位、日志和重启脚本。',
    '常见问题与风险边界｜原帖使用的 llama.cpp HIP 构建对应特定提交与 Qwen3.8 模板，换模型家族或驱动后需重新验证。KV q4_0、MTP 和 128K 都会改变显存与质量；不要复制完整脚本后跳过环境核对。',
    '留给社区的讨论问题｜在混合 AMD/NVIDIA 工作站中，你更愿意通过容器、进程环境还是不同推理后端来隔离 GPU？怎样证明隔离真的生效？',
  ]),
]
